import SiteNavbar from "@/components/SiteNavbar"
import Footer from "@/components/Footer"
import favicon from '@/assets/favicon.ico'
import '@/css/main.scss'

export const metadata = {
    title: 'PROJXON',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href={favicon.src} sizes="any" />
                <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@100..900&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
            </head>
            <body>
                <div className="content">
                    <SiteNavbar />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    )
}