import "./index.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "PROJXON",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
