import "@/styles/index.css";
import "@/styles/App.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "aos/dist/aos.css";

import ScrollToTop from "@/components/ScrollToTop";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "PROJXON",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </head>
      <body>
        <NavBar />
        <ScrollToTop />
        {children}
        <Footer />
      </body>
    </html>
  );
}
